const initData =
  [
    {
      "title": "Broccoli 🥦 florettes 12oz",
      "aisle": "Frozen",
      "price": "1.16",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:15:00.543Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Stir fry veggies 🍜",
      "aisle": "Frozen",
      "price": "2.67",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:11:24.498Z",
      "days": 1
    },
    {
      "title": "Garlic 🧄",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": true,
      "lastPurchase": "2024-12-01T23:15:04.317Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Mozzarella 🍕",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-11-27T23:34:20.569Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Pasta 🍝",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:15:54.923Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Propane",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:16:12.178Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Rice 🌾",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": true,
      "lastPurchase": "2024-12-01T23:16:43.051Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Salmon 🐟",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:15:36.638Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Tent sticks and rope",
      "aisle": "Moro",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-11-29T21:11:22.069Z",
      "days": 0
    },
    {
      "title": "Ahi 🐟",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:22:10.067Z",
      "days": 1
    },
    {
      "title": "Apples 🍎",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:23:13.992Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Baguette 🥖",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": true,
      "lastPurchase": "2024-10-25T19:08:27.349Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Chibata 🥪",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:21:50.671Z",
      "days": 1
    },
    {
      "title": "Sour Dough Bread 🍞",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:16:55.018Z",
      "days": 1,
      "display": true
    },
    {
      "title": "White Onions 🧅",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": true,
      "lastPurchase": "2024-12-01T23:23:26.983Z",
      "days": 1
    },
    {
      "title": "Chocolate milk 🍫🥛",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:25:05.014Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Coffee ☕",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:23:32.487Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Litter 7lb bag 🐈",
      "aisle": "Weekly",
      "price": "1.96",
      "quantity": 3,
      "tax": false,
      "cart": false,
      "select": true,
      "lastPurchase": "2024-11-18T21:23:01.812Z",
      "days": 1,
      "color": "#bdb286",
      "display": true
    },
    {
      "title": "Onion 🧅",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": true,
      "lastPurchase": "2024-10-29T17:43:42.114Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Peppers and Onion🫑🧅",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:25:07.437Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Red onion 🧅",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": true,
      "lastPurchase": "2024-12-01T23:25:16.195Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Spinach 🥬",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-10-29T17:43:27.472Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Water 💦",
      "aisle": "Weekly",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-11-03T20:55:33.010Z",
      "days": 1,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Hamburgers 🍔",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:25:50.379Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Olive oil 🫒",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:25:59.772Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Potatoes 🥔",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:25:53.964Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Salt 🧂",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:26:28.357Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Tomato sauce 🍅",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:25:35.128Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Eggs 🥚",
      "aisle": "cats",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:26:48.211Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Ground beef 🥩",
      "aisle": "cats",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": true,
      "lastPurchase": "2024-12-01T23:26:34.020Z",
      "days": 1
    },
    {
      "title": "Ground turkey 🦃",
      "aisle": "cats",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": true,
      "lastPurchase": "2024-11-18T15:05:14.844Z",
      "days": 1
    },
    {
      "title": "Camping lighter 🔥",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Cash 💰",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:50:58.254Z",
      "days": 1,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Charcoal 🔥",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:52:04.150Z",
      "days": 1,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Dry ice 🥶",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-02-14T17:41:08.570Z",
      "days": 1,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Duct tape 📦",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-03T19:35:31.900Z",
      "days": 109,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Ice blocks 🥶",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:52:15.936Z",
      "days": 1,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Key 🗝️",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Pulled pork 🍖",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T17:09:53.538Z",
      "days": 53,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Sausage 🌭",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-07T02:31:23.460Z",
      "days": 198,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Squid 🦑",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-02T21:34:56.615Z",
      "days": 80,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Sun block ☀️",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:52:34.787Z",
      "days": 1,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Wax 🏄‍♂️",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-19T00:34:25.452Z",
      "days": 1,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Cutting board 📦 15x21 B5",
      "aisle": "B5",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-06-30T01:56:07.260Z",
      "days": 0,
      "display": true
    },
    {
      "title": "Acai 🥣",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Almond milk 🥛",
      "aisle": "Baja",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-30T00:14:08.272Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Apple juice 🍎",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-13T20:07:06.214Z",
      "days": 191,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Brown rice and broccoli",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Carrots 🥕",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-17T14:25:47.061Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Chia seed pudding",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-18T22:09:56.882Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Chives",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:04:34.625Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Coffee pot ☕",
      "aisle": "Baja",
      "price": "10.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-10T23:49:41.458Z",
      "days": 10,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Ear plugs",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fat wood 🪵",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:52:56.230Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fishing license 🪪",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-18T16:26:38.333Z",
      "days": 247,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fishing line 🎣",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-18T16:26:38.333Z",
      "days": 247,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fishing rods 🎣",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:53:23.723Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fork, Spoons and Knife 🔪",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "French fries 🍟",
      "aisle": "Baja",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-06-12T23:52:54.939Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Gas tanks ⛽",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Ice cream🍦",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Ice 🥶",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:53:30.472Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Meatballs 🥔",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Memory card",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-07-10T16:50:54.906Z",
      "days": 225,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Milk 🥛",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-07-15T16:15:31.327Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Mosquito net 🥅",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:53:46.980Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Passports 🪪",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Peas",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Raisens 🍇",
      "aisle": "Baja",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:54:11.612Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Ranch 🍼",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:52:52.254Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Shovel",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:54:47.364Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Sleeping bags ⛺",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Solar charger ☀️",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Strawberries 🍓",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "SX-530 Battery 🔋",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-07-10T16:50:54.906Z",
      "days": 225,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Tackle box 🎣",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-04-16T15:29:46.449Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Throw net 🎣",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-18T16:26:38.333Z",
      "days": 247,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Toothpaste 🦷",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Vanilla",
      "aisle": "Baja",
      "price": "2.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-26T15:30:02.055Z",
      "days": 0,
      "display": true
    },
    {
      "title": "Water jug 🏺",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Zip lock bags 🤐",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-23T22:18:35.686Z",
      "days": 59,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Seat post 30.9 🚲",
      "aisle": "Bike",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-12T21:16:21.480Z",
      "days": 161,
      "color": "#772c25",
      "display": true
    },
    {
      "title": "Vanilla Extract",
      "aisle": "Breakfast",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-08-30T17:27:00.321Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Eggplant 🍆",
      "aisle": "Garden",
      "price": "6.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-03-06T21:31:58.082Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Red lettuce 🥬",
      "aisle": "Garden",
      "price": "5.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:15:30.328Z",
      "days": 1,
      "color": "#f963a5",
      "display": true
    },
    {
      "title": "Breakfast stuff 🥚",
      "aisle": "Indo",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Outlet Adapters 🔌",
      "aisle": "Indo",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Cat food 😺",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-18T15:00:02.057Z",
      "days": 1,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Cheese 🧀",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:57:35.438Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Garlic bread 🥖",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-06-12T23:51:37.625Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Green beans 🫘",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:57:29.327Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Iceberg lettuce shredded 🥬",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-17T14:18:34.841Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Mango 🥭",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:57:45.237Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Peanut butter 🥜",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-07-19T20:22:53.304Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Pineapple 🍍",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-25T19:29:27.684Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Shrimp 🍤",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:58:04.053Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Toilet paper 🧻",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:57:52.992Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Yellow squash 🥒",
      "aisle": "Monthly",
      "price": "6.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-02-18T02:08:59.129Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Zucchini 🥒",
      "aisle": "Monthly",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:57:21.562Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Uni 🦀",
      "aisle": "New",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-28T00:21:54.593Z",
      "days": 146,
      "color": "#bf33a5",
      "display": true
    },
    {
      "title": "Hydroponic ",
      "aisle": "New Job",
      "price": "100.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:47:03.848Z",
      "days": 0
    },
    {
      "title": "Juicer",
      "aisle": "New Job",
      "price": "200.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:48:47.499Z",
      "days": 0
    },
    {
      "title": "Moka Pot",
      "aisle": "New Job",
      "price": "50.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:47:48.701Z",
      "days": 0
    },
    {
      "title": "Pet Vet",
      "aisle": "New Job",
      "price": "800.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:53:23.227Z",
      "days": 0
    },
    {
      "title": "Propane Tank",
      "aisle": "New Job",
      "price": "50.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:42:07.996Z",
      "days": 0
    },
    {
      "title": "Solar",
      "aisle": "New Job",
      "price": "300.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:45:29.719Z",
      "days": 0
    },
    {
      "title": "Starlink",
      "aisle": "New Job",
      "price": "130.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:40:01.152Z",
      "days": 0
    },
    {
      "title": "Thermostat",
      "aisle": "New Job",
      "price": "500.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:46:20.787Z",
      "days": 0
    },
    {
      "title": "Travel neck brace",
      "aisle": "New Job",
      "price": "80.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:50:19.969Z",
      "days": 0
    },
    {
      "title": "Water Tank",
      "aisle": "New Job",
      "price": "50.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:43:14.002Z",
      "days": 0
    },
    {
      "title": "Wetsuit",
      "aisle": "New Job",
      "price": "150.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:41:09.221Z",
      "days": 0
    },
    {
      "title": "Wyze vacuum",
      "aisle": "New Job",
      "price": "100.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-20T18:39:12.229Z",
      "days": 0
    },
    {
      "title": "Beans 15 mix 🫘",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-23T17:04:53.945Z",
      "days": 273,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Bison 🦬",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-26T04:15:57.249Z",
      "days": 148,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Bulgar 🍚",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-22T20:17:37.083Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Celery",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-17T14:25:37.456Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Cherries 🍒",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-07-11T20:33:48.501Z",
      "days": 224,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Chowder 🍲",
      "aisle": "Smart and Final",
      "price": "NaN",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T03:31:57.198Z",
      "days": 54,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Club soda 🥤",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-28T19:05:25.206Z",
      "days": 84,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Dishwasher detergent 🫧",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-15T21:53:45.526Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Ham 🍖",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-13T21:35:34.774Z",
      "days": 283,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Hummus 🫓",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-12T21:17:00.180Z",
      "days": 161,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Ice pop 🚀",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-05T01:52:20.655Z",
      "days": 169,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "kaffir lime leaves 2 🍋‍🟩",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-10-19T23:21:08.552Z",
      "days": 124,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Laundry detergent 🫧",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Lemon 🍋",
      "aisle": "Smart and Final",
      "price": "0.50",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-04T18:25:05.628Z",
      "days": 200,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Lentils 🍜",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-05T03:00:13.099Z",
      "days": 292,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Pancake mix 🥞",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-11T16:10:08.006Z",
      "days": 101,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Parmisean 🧀",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-13T15:34:16.785Z",
      "days": 283,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Pesto 🫙",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T18:58:56.003Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Pizza 🍕",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:15:08.139Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Ponzu 🍋",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Quinuao 🍚",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-05T03:00:13.099Z",
      "days": 292,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Shallots 6 🧅",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-10-19T23:21:08.552Z",
      "days": 124,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "shrimp paste / terasi 🦐",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-10-19T23:21:08.552Z",
      "days": 124,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Soy 🍣",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Sugar 🍬",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-09T14:40:23.620Z",
      "days": 11,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Tumurick 🫚",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Seafood 🦞",
      "aisle": "Sprouts",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-22T20:19:53.160Z",
      "days": 1,
      "color": "#aa5887",
      "display": true
    },
    {
      "title": "Alcohol 🍹",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T17:09:53.538Z",
      "days": 53,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Beer 🍺",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-02T21:34:56.615Z",
      "days": 80,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Cilantro",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-03T18:12:58.952Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Salad 🥗",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-02T14:14:49.732Z",
      "days": 110,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Salsa 🌮",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-27T16:47:17.221Z",
      "days": 238,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Serranos 🌶️",
      "aisle": "Tienda",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-26T15:19:45.069Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Tortillas 🌮",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-29T19:48:09.693Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Vodka 🍹",
      "aisle": "Vons",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-05-01T01:26:58.382Z",
      "days": 1,
      "color": "#bdb286",
      "display": true
    },
    {
      "title": "Avocado oil 🥑",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-01T23:51:35.926Z",
      "days": 0
    },
    {
      "title": "Bagels 🥯",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-03-29T21:29:04.351Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Baking soda",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-07-08T14:01:27.296Z",
      "days": 0,
      "display": true
    },
    {
      "title": "Balsamic vinegar 🍇",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-07-19T20:24:30.075Z",
      "days": 0
    },
    {
      "title": "Basil",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-05-08T16:47:37.238Z",
      "days": 0,
      "display": true
    },
    {
      "title": "Breakfast sausage 🌭 ",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-25T00:17:25.187Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Broccoli 🥦 Coliflour ",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-25T00:18:55.509Z",
      "days": 0
    },
    {
      "title": "Bucket 🪣",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-19T22:56:05.043Z",
      "days": 0
    },
    {
      "title": "Cardamon 🫚",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-07-03T23:45:50.933Z",
      "days": 0,
      "display": true
    },
    {
      "title": "Chocolate chips 🍫",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-06-15T13:25:56.320Z",
      "days": 0,
      "display": true
    },
    {
      "title": "Clamoto 🍅",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-29T17:40:18.540Z",
      "days": 1
    },
    {
      "title": "Cocao chocolate 🍫",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-06-12T23:48:31.880Z",
      "days": 0,
      "display": true
    },
    {
      "title": "Feta 🧀",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-17T14:19:58.921Z",
      "days": 1
    },
    {
      "title": "Firewood 🔥",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-27T23:33:54.663Z",
      "days": 0
    },
    {
      "title": "Ginger Powder 🫚",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-06-20T15:11:57.790Z",
      "days": 0,
      "display": true
    },
    {
      "title": "Hose 75' brass bullet 🚒",
      "aisle": "Walmart",
      "price": "20.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:14:33.795Z",
      "days": 1,
      "color": "#a923e4",
      "display": true
    },
    {
      "title": "Litter 20lb 🐈",
      "aisle": "Walmart",
      "price": "5.39",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-18T21:21:44.724Z",
      "days": 0
    },
    {
      "title": "Litter Container 🐈",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-19T22:56:16.660Z",
      "days": 0
    },
    {
      "title": "Pickled onions 🧅",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-17T14:20:03.476Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Pinto beans 🫘",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-29T19:48:22.734Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Popcorn 🍿",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-20T22:28:42.717Z",
      "days": 0
    },
    {
      "title": "Pork chops",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-25T00:17:18.813Z",
      "days": 0
    },
    {
      "title": "Pressure washer 🚒",
      "aisle": "Walmart",
      "price": "12.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-18T00:15:38.784Z",
      "days": 3,
      "color": "#a923e4",
      "display": true
    },
    {
      "title": "Rice vinegar 🍘",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-17T14:20:42.614Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Rolls 🥐",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-07-19T20:22:25.216Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Soy chorizo 🍛",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-04-19T00:53:50.677Z",
      "days": 0,
      "display": true
    },
    {
      "title": "Sriracha Garlic Chile Sauce",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-17T14:20:48.611Z",
      "days": 1,
      "display": true
    },
    {
      "title": "tea🍵",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-18T22:42:06.789Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Tomatoes 🍅 roma 3ct",
      "aisle": "Walmart",
      "price": "1.10",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-15T21:55:40.919Z",
      "days": 1
    },
    {
      "title": "Tostadas 🌮",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T19:00:47.448Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Turkey 🦃",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-12T16:05:53.626Z",
      "days": 0
    },
    {
      "title": "Walnuts 🥜",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 5,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:14:48.095Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Watermelon 🍉",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-15T21:53:58.699Z",
      "days": 1
    },
    {
      "title": "Avocados 🥑",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-17T14:21:13.900Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Bananas 🍌",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 5,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-09T23:20:11.893Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Beets",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-17T14:21:29.576Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Bread 🍞",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-09T23:14:42.058Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Carrots and peas 🥕🫛",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-06-12T23:49:50.084Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Chicken 🍗",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T19:01:22.068Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Corn 🌽",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-03-13T16:01:30.729Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Crackers 🍪",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Cucumber 🥒",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-24T20:52:52.481Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Fruit 🍑",
      "aisle": "Weekly",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-06-12T23:50:00.587Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Ginger 🫚",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-29T17:42:41.447Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Limes 🍋‍🟩",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-24T20:52:46.134Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Mushrooms 🍄",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T19:01:05.205Z",
      "days": 1,
      "display": true
    },
    {
      "title": "Yogurt 🐮",
      "aisle": "Weekly",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T19:01:29.539Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "22\" pole ",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-02T14:14:49.732Z",
      "days": 110,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Apple sauce 🍏",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "BBQ Sauce 🫙",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T19:01:46.995Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Beans 🫘",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-29T19:48:20.485Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Black Pepper 🧂",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Buns 🍔",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-30T01:12:08.711Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Butter 🧈",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T19:01:52.643Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Chips",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-02-23T20:14:01.159Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Cinnamon",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Coconut 🥥",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-30T01:11:54.641Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Cyan Pepper 🌶️",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Dish soap 🫧",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T19:01:57.401Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Garlic Powder 🧄",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-03-29T21:30:20.589Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Ginger beer 🫚",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-06-12T23:49:08.360Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Granola 🥣",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Juice 🥤",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Ketchup 🍅",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Oatmeal 🥣",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-09T23:16:18.724Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Paper towels 🧻",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T19:02:08.004Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Pina Colada 🍹",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Soap 🧼",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Tylenol 500 mg 💊",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-10-11T19:03:00.142Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Vegetable oil 🛢️",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Wipes 🧻",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Burner 🔥 ",
      "aisle": "big5",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#69019c",
      "display": true
    },
    {
      "title": "Hatch lock 🔒",
      "aisle": "big5",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-29T19:38:14.408Z",
      "days": 144,
      "color": "#69019c",
      "display": true
    },
    {
      "title": "Tent fan light 🪭",
      "aisle": "big5",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T17:09:53.538Z",
      "days": 53,
      "color": "#69019c",
      "display": true
    },
    {
      "title": "Chicken liver🐔",
      "aisle": "cats",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-12T16:08:47.849Z",
      "days": 0
    },
    {
      "title": "Chicken Thighs 🍗",
      "aisle": "cats",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-12T16:05:26.940Z",
      "days": 0
    },
    {
      "title": "Chicken 🐔 Broth plain ",
      "aisle": "cats",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-18T21:51:36.369Z",
      "days": 1
    },
    {
      "title": "Rabbit 🐇",
      "aisle": "cats",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-12T16:08:16.656Z",
      "days": 0
    },
    {
      "title": "Sardine oil 500 mg 🐟",
      "aisle": "cats",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-12T16:09:30.697Z",
      "days": 0
    },
    {
      "title": "Taurine",
      "aisle": "cats",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-09-12T16:09:55.503Z",
      "days": 0
    },
    {
      "title": "Mint 🥬",
      "aisle": "garden",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-28T19:05:25.206Z",
      "days": 84,
      "color": "#5344be",
      "display": true
    },
    {
      "title": "Spider plant 🌵",
      "aisle": "hydroponics",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-02T20:19:23.258Z",
      "days": 171,
      "color": "#cf11a3",
      "display": true
    },
    {
      "title": "Telancias",
      "aisle": "hydroponics",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-22T03:31:57.811Z",
      "days": 152,
      "color": "#cf11a3",
      "display": true
    },
    {
      "title": "Lobster roll 🦞",
      "aisle": "iron",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-28T00:21:54.593Z",
      "days": 146,
      "color": "#bf33a5",
      "display": true
    },
    {
      "title": "Octopus 🐙",
      "aisle": "iron",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-28T00:21:54.593Z",
      "days": 146,
      "color": "#bf33a5",
      "display": true
    },
    {
      "title": "Oysters 🦀",
      "aisle": "iron",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-11-19T00:33:29.739Z",
      "days": 1,
      "color": "#bf33a5",
      "display": true
    },
    {
      "title": "Battery 100 AH 🔋",
      "aisle": "pep boys",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-07T17:48:32.045Z",
      "days": 197,
      "color": "#5f2e83",
      "display": true
    },
    {
      "title": "Oil Filter K&N HP-1008 🛢️",
      "aisle": "pep boys",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-02-18T02:10:53.063Z",
      "days": 1,
      "color": "#5f2e83",
      "display": true
    },
    {
      "title": "Cat feeder Let Bistro 5lb 🐈",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-06T16:53:57.102Z",
      "days": 198,
      "color": "#35468f",
      "display": true
    },
    {
      "title": "Cheesy poofs 🐈",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-10-02T18:56:59.519Z",
      "days": 141,
      "color": "#35468f",
      "display": true
    },
    {
      "title": "Grass garden 🏡",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-07-28T15:50:33.685Z",
      "days": 207,
      "color": "#35468f",
      "display": true
    },
    {
      "title": "Motor oil SAE 5w 30 🛢️",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 2,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2024-02-18T02:10:43.926Z",
      "days": 1,
      "color": "#35468f",
      "display": true
    },
    {
      "title": "Petmate portion right",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-29T19:38:14.408Z",
      "days": 144,
      "color": "#35468f",
      "display": true
    }
  ]
export default initData;