const initData = 
[
    {
      "title": "Water",
      "aisle": "A",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-25T22:18:07.164Z",
      "days": 1,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Almond milk",
      "aisle": "Baja",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:04:53.970Z",
      "days": 0
    },
    {
      "title": "Carrots",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-26T15:18:13.934Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Chives",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:04:34.625Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Chia seed pudding",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:04:34.625Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "French fries",
      "aisle": "Baja",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-22T20:15:00.011Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fruit",
      "aisle": "Baja",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-22T20:15:00.011Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Garlic bread",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-22T20:17:01.801Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Milk",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-22T20:17:08.486Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Oatmeal",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-22T20:17:08.486Z",
      "days": 1,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Raisans",
      "aisle": "Baja",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-26T15:27:17.898Z",
      "days": 0
    },
    {
      "title": "Vanilla",
      "aisle": "Baja",
      "price": "2.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-26T15:30:02.055Z",
      "days": 0
    },
    {
      "title": "Vanilla Extract",
      "aisle": "Breakfast",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:11:42.478Z",
      "days": 0
    },
    {
      "title": "Eggplant",
      "aisle": "Garden",
      "price": "6.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-25T20:14:02.973Z",
      "days": 0
    },
    {
      "title": "Red lettuce",
      "aisle": "Garden",
      "price": "5.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:15:30.328Z",
      "days": 1,
      "color": "#f963a5",
      "display": true
    },
    {
      "title": "Bulgar",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-22T20:17:37.083Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Celery",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-22T20:19:13.797Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Garlic",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:15:20.498Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Pizza",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:15:08.139Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Spinach",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:26:53.259Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Seafood",
      "aisle": "Sprouts",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-22T20:19:53.160Z",
      "days": 1,
      "color": "#aa5887",
      "display": true
    },
    {
      "title": "Avacados",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 5,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:15:05.526Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Bananas",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 5,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:15:01.279Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Eggs",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:14:55.356Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Serranos",
      "aisle": "Tienda",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-26T15:19:45.069Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Tomatoes",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 5,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:14:48.095Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Walnuts",
      "aisle": "Walmart",
      "price": "0.00",
      "quantity": 5,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-19T22:14:48.095Z",
      "days": 1,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Hose 75' brass bullet",
      "aisle": "Walmart",
      "price": "20.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:14:33.795Z",
      "days": 1,
      "color": "#a923e4",
      "display": true
    },
    {
      "title": "BBQ Sauce",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:14:29.643Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Buns",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:14:26.977Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Chips",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:14:15.295Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Hamburgers",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-19T22:13:16.596Z",
      "days": 1,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Yellow squash",
      "aisle": "garden",
      "price": "6.00",
      "quantity": 1,
      "tax": false,
      "cart": true,
      "select": false,
      "lastPurchase": "2021-02-25T20:14:44.339Z",
      "days": 0
    },
    {
      "title": "Zucchini",
      "aisle": "garden",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-22T20:19:22.468Z",
      "days": 1,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Camping lighter",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Cash",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-02T14:14:49.732Z",
      "days": 110,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Cat food",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-15T14:55:58.004Z",
      "days": 5,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Charcoal",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Dry ice",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-06T16:54:27.228Z",
      "days": 198,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Duct tape",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-03T19:35:31.900Z",
      "days": 109,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Ice blocks",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-09T01:07:06.594Z",
      "days": 12,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Key",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Pulled pork",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T17:09:53.538Z",
      "days": 53,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Sausage",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-07T02:31:23.460Z",
      "days": 198,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Squid",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-02T21:34:56.615Z",
      "days": 80,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Sun block",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T17:09:53.538Z",
      "days": 53,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Wax",
      "aisle": "A",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#338a80",
      "display": true
    },
    {
      "title": "Acai",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Apple juice",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-13T20:07:06.214Z",
      "days": 191,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Broccoli",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Brown rice and broccoli",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Rice",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Cheese",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Coffee pot",
      "aisle": "Baja",
      "price": "10.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-10T23:49:41.458Z",
      "days": 10,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Corn",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Ear plugs",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fat wood",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fishing license",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-18T16:26:38.333Z",
      "days": 247,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fishing line",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-18T16:26:38.333Z",
      "days": 247,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fishing rode",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-18T16:26:38.333Z",
      "days": 247,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Gas tanks",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Green beans",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Ice",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Ice cream",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Mango",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Rasins",
      "aisle": "Baja",
      "price": "3.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Meatballs",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Memory card",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-07-10T16:50:54.906Z",
      "days": 225,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Mosquito net",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Passports",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Fork, Spoons and Knife",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Peas",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Pineapple",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-08T21:28:23.144Z",
      "days": 12,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Propane",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Ranch",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Shovel",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-07-09T18:47:32.167Z",
      "days": 226,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Shrimp",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Sleeping bags",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Solar charger",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Strawberries",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "SX-530 Battery",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-07-10T16:50:54.906Z",
      "days": 225,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Tackle box",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T03:30:52.686Z",
      "days": 53,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Throw net",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-18T16:26:38.333Z",
      "days": 247,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Toilet paper",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Toothpaste",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Outlet Adapters",
      "aisle": "Indo",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Breakfast stuff",
      "aisle": "Indo",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Water jug",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Yogurt",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T03:30:52.686Z",
      "days": 53,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Zip lock bags",
      "aisle": "Baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-23T22:18:35.686Z",
      "days": 59,
      "color": "#b8e522",
      "display": true
    },
    {
      "title": "Seat post 30.9",
      "aisle": "Bike",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-12T21:16:21.480Z",
      "days": 161,
      "color": "#772c25",
      "display": true
    },
    {
      "title": "Beans 15 mix",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-23T17:04:53.945Z",
      "days": 273,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Bison",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-26T04:15:57.249Z",
      "days": 148,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Cherries",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-07-11T20:33:48.501Z",
      "days": 224,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Chicken",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-08T19:43:38.050Z",
      "days": 12,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Chowder",
      "aisle": "Smart and Final",
      "price": "NaN",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T03:31:57.198Z",
      "days": 54,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Club soda",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-28T19:05:25.206Z",
      "days": 84,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Dishwasher detergent",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Ham",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-13T21:35:34.774Z",
      "days": 283,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Hummus",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-12T21:17:00.180Z",
      "days": 161,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Ice pop",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-05T01:52:20.655Z",
      "days": 169,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Avacados",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-05T01:52:20.655Z",
      "days": 169,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "kaffir lime leaves 2",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-10-19T23:21:08.552Z",
      "days": 124,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Laundry detergent",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Lemons",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-04T18:25:05.628Z",
      "days": 200,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Lentils",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-05T03:00:13.099Z",
      "days": 292,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Limes",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-07T02:31:23.460Z",
      "days": 198,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Pancake mix",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-11T16:10:08.006Z",
      "days": 101,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Parmisean",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-13T15:34:16.785Z",
      "days": 283,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Pasta",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-11T15:02:41.191Z",
      "days": 254,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Pesto",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Ponzu",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Quinuao",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-05-05T03:00:13.099Z",
      "days": 292,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Shallots 6",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-10-19T23:21:08.552Z",
      "days": 124,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "shrimp paste / terasi .5tbls",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-10-19T23:21:08.552Z",
      "days": 124,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Soy",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Sugar",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-09T14:40:23.620Z",
      "days": 11,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Tumurick",
      "aisle": "Smart and Final",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T00:57:35.566Z",
      "days": 298,
      "color": "#47f2d7",
      "display": true
    },
    {
      "title": "Alcohol",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T17:09:53.538Z",
      "days": 53,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Beer",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-02T21:34:56.615Z",
      "days": 80,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Cilantro",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-27T16:47:17.221Z",
      "days": 238,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Salad",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-02T14:14:49.732Z",
      "days": 110,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Salsa",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-06-27T16:47:17.221Z",
      "days": 238,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Tortillas",
      "aisle": "Tienda",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-04-29T01:14:33.544Z",
      "days": 298,
      "color": "#a8195b",
      "display": true
    },
    {
      "title": "Litter",
      "aisle": "Vons",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-14T16:35:02.547Z",
      "days": 98,
      "color": "#bdb286",
      "display": true
    },
    {
      "title": "Vodka",
      "aisle": "Vons",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T03:31:57.198Z",
      "days": 54,
      "color": "#bdb286",
      "display": true
    },
    {
      "title": "Pressure washer",
      "aisle": "Walmart",
      "price": "12.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-18T00:15:38.784Z",
      "days": 3,
      "color": "#a923e4",
      "display": true
    },
    {
      "title": "22\" pole ",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-02T14:14:49.732Z",
      "days": 110,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Apple sauce",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Beans",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Black Pepper",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Cinnimon",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Coconut",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Coffee",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2021-02-10T23:50:43.026Z",
      "days": 10,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Crackers",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Cyan Pepper",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Dish soap",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Garlic Powder",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Ginger beer",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Granola",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Juice",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Ketchup",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Olive oil",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Onion",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Outmeal",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Paper towels",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Butter",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Peanut butter",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Pina Colada",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Potatoes",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Rice",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Salt",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Soap",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Tomato sauce",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Tylenol 500 mg",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Vegetable oil",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Wipes",
      "aisle": "baja",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#a0306a",
      "display": true
    },
    {
      "title": "Burner",
      "aisle": "big5",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-30T16:46:58.306Z",
      "days": 52,
      "color": "#69019c",
      "display": true
    },
    {
      "title": "Hatch lock",
      "aisle": "big5",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-29T19:38:14.408Z",
      "days": 144,
      "color": "#69019c",
      "display": true
    },
    {
      "title": "Tent fan light",
      "aisle": "big5",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-12-29T17:09:53.538Z",
      "days": 53,
      "color": "#69019c",
      "display": true
    },
    {
      "title": "Mint",
      "aisle": "garden",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-28T19:05:25.206Z",
      "days": 84,
      "color": "#5344be",
      "display": true
    },
    {
      "title": "Spider plant",
      "aisle": "hydroponics",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-02T20:19:23.258Z",
      "days": 171,
      "color": "#cf11a3",
      "display": true
    },
    {
      "title": "Telancias",
      "aisle": "hydroponics",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-22T03:31:57.811Z",
      "days": 152,
      "color": "#cf11a3",
      "display": true
    },
    {
      "title": "Lobster roll",
      "aisle": "iron",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-28T00:21:54.593Z",
      "days": 146,
      "color": "#bf33a5",
      "display": true
    },
    {
      "title": "Octopus",
      "aisle": "iron",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-28T00:21:54.593Z",
      "days": 146,
      "color": "#bf33a5",
      "display": true
    },
    {
      "title": "Oysters",
      "aisle": "iron",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-28T00:21:54.593Z",
      "days": 146,
      "color": "#bf33a5",
      "display": true
    },
    {
      "title": "Uni",
      "aisle": "iron",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-28T00:21:54.593Z",
      "days": 146,
      "color": "#bf33a5",
      "display": true
    },
    {
      "title": "Battery 100 AH",
      "aisle": "pep boys",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-07T17:48:32.045Z",
      "days": 197,
      "color": "#5f2e83",
      "display": true
    },
    {
      "title": "Oil Filter K&N HP-1008",
      "aisle": "pep boys",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-02T14:14:49.732Z",
      "days": 110,
      "color": "#5f2e83",
      "display": true
    },
    {
      "title": "Cat feeder Let Bistro 5lb",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-08-06T16:53:57.102Z",
      "days": 198,
      "color": "#35468f",
      "display": true
    },
    {
      "title": "Cheesy poofs",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-10-02T18:56:59.519Z",
      "days": 141,
      "color": "#35468f",
      "display": true
    },
    {
      "title": "Grass garden",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-07-28T15:50:33.685Z",
      "days": 207,
      "color": "#35468f",
      "display": true
    },
    {
      "title": "Motor oil SAE 5w 30",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 1,
      "tax": true,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-11-02T14:14:49.732Z",
      "days": 110,
      "color": "#35468f",
      "display": true
    },
    {
      "title": "Petmate portion right",
      "aisle": "pet smart",
      "price": "0.00",
      "quantity": 1,
      "tax": false,
      "cart": false,
      "select": false,
      "lastPurchase": "2020-09-29T19:38:14.408Z",
      "days": 144,
      "color": "#35468f",
      "display": true
    },
];
export default initData;