const initAndroidPlayers = [
    {
        "name": "john",
        "score": 0,
        "standard": true,
        "ping pong": true,
        "golf": true,
        "cornhole": true,
        "darts": true,
        "dominos": true,
        "horse": true,
        "horseshoes": true,
        "bocci": true,
        "surf": true,
        "surfScore": 0,
        "dominoScore": 0,
        "golfScores": [
            5,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "golfGIR": [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ],
        "golfFW": [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ],
        "golfPutts": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "surfScores": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        ],
        "surfJerseyColor": 4,
        "surfPriority": 0,
        "cricketScores": [
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "ping pongScore": 0,
        "dartsScore": 0,
        "horseScore": 1,
        "horseshoesScore": 0,
        "bocciScore": 0,
        "golfScore": 5,
        "standardScore": 0,
        "scrabble": true,
        "scrabbleScore": 0,
        "interferenceCount": 0,
        "golfShots": [
            [
                {},
                {
                    "coords": [
                        -117.241838,
                        33.0799961
                    ],
                    "distance": null,
                    "club": "Driver"
                },
                {
                    "coords": [
                        -117.2417557,
                        33.0800134
                    ],
                    "distance": 10.05,
                    "club": "3 Hybrid"
                },
                {
                    "coords": [
                        -117.24184,
                        33.0800069
                    ],
                    "distance": 10.26,
                    "club": "5 Hybrid"
                },
                {
                    "coords": [
                        -117.2418386,
                        33.0800076
                    ],
                    "distance": 0.17,
                    "club": "9 Iron"
                },
                {
                    "coords": [
                        -117.2418525,
                        33.0801186
                    ],
                    "distance": 6.41,
                    "club": "P Wedge"
                },
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ]
        ]
    },
    {
        "name": "Gina",
        "score": 0,
        "standard": false,
        "ping pong": true,
        "golf": false,
        "cornhole": true,
        "darts": true,
        "dominos": true,
        "horse": false,
        "horseshoes": false,
        "bocci": true,
        "surf": false,
        "surfScore": 0,
        "dominoScore": 0,
        "golfScores": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "golfGIR": [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ],
        "golfFW": [
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false
        ],
        "golfPutts": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "surfScores": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        ],
        "surfJerseyColor": 0,
        "surfPriority": 0,
        "cricketScores": [
            0,
            0,
            0,
            0,
            0,
            0,
            0
        ],
        "golfShots": [
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ],
            [
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            ]
        ],
        "dartsScore": 0,
        "horseshoesScore": 0,
        "golfScore": 0
    }
]

export default initAndroidPlayers;