// src/components/VotingForm/actions.js

export const actionTypes = {
    UPDATE_FIELD: 'UPDATE_FIELD',
    EMAIL_VALIDATING: 'EMAIL_VALIDATING',
    EMAIL_VALIDATED: 'EMAIL_VALIDATED',
    PASSWORD_STRENGTH: 'PASSWORD_STRENGTH',
    SUBMIT_SUCCESS: 'SUBMIT_SUCCESS',
    SUBMIT_ERROR: 'SUBMIT_ERROR',
    RESET: 'RESET',
};