[
    {
        'description':'Eat',
        'type':'checkbox',
        'time':0,
        'currentTime':0,
        'activated':false,
        'completed':false
    },
    {
        'description':'Surf',
        'type':'timer',
        'time':7200,
        'currentTime':6860,
        'activated':false,
        'completed':false,
        'startTime':1734967345939,
        'elapsedTime':7200
    },
    {
        'description':'Sleep 20 minutes',
        'type':'timer',
        'time':1200,
        'currentTime':1200,
        'activated':false,
        'completed':false,
        'startTime':1718995132263,
        'elapsedTime':15
    }
]